import { afterEach, describe, expect, it } from 'vitest'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import jsonld from 'jsonld'

import { capabilitiesFor } from '../src/emit/capability.js'
import { emit, parseArtifact, retargetVersionHeader, stripComments } from '../src/emit/emit.js'
import { resolveModelText } from '../src/model/resolve.js'
import { SourceIndex } from '../src/source/index-file.js'

const GOLDEN = fileURLToPath(new URL('./fixtures/golden/', import.meta.url))
const DOCUMENTS = fileURLToPath(new URL('./fixtures/documents/', import.meta.url))
const UPDATE = process.env['UPDATE_GOLDEN'] === '1'

const UPSTREAM = 'https://example.org/vocab/core.jsonld'
const UPSTREAM_BODY = {
  '@context': {
    schema: 'https://schema.org/',
    name: 'schema:name',
    homepage: { '@id': 'schema:url', '@type': '@id' },
  },
}

const dirs: string[] = []
afterEach(() => {
  while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true })
})

function resolveContext(iri: string): unknown {
  return iri === UPSTREAM ? UPSTREAM_BODY : undefined
}

function build(text: string, path = 'model.jsonld.yaml') {
  const source = SourceIndex.parse(text, { path })
  const { ir, findings } = resolveModelText(text, path)
  return { ir: ir!, source, resolveFindings: findings }
}

/** A golden file detects unintended churn; it never proves correctness. */
function golden(name: string, actual: string): void {
  const path = join(GOLDEN, name)
  if (UPDATE || !existsSync(path)) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, actual)
    return
  }
  expect(actual, `golden ${name} — rerun with UPDATE_GOLDEN=1 if intended`).toBe(
    readFileSync(path, 'utf8'),
  )
}

const LAYERED = `jsonld: "1"
namespace:
  prefix: ex
  base: https://example.org/ns#
mode: "1.1"
prefixes:
  schema: https://schema.org/
uses:
  - iri: ${UPSTREAM}
    integrity: sha256-ZZZZ
terms:
  title:
    id: aaa111
    "@id": ex:title
  author:
    id: bbb222
    "@id": schema:author
    "@type": "@id"
  tags:
    id: ccc333
    "@id": ex:tag
    "@container": "@set"
`

const STANDALONE = `jsonld: "1"
namespace:
  prefix: ex
  base: https://example.org/ns#
terms:
  name:
    id: aaa111
    "@id": ex:name
  author:
    id: bbb222
    "@id": ex:author
    "@type": "@id"
  tags:
    id: ccc333
    "@id": ex:tag
    "@container": "@set"
`

const MODE_10 = `jsonld: "1"
namespace:
  prefix: ex
  base: https://example.org/ns#
mode: "1.0"
terms:
  name:
    id: aaa111
    "@id": ex:name
    "@protected": true
  nested:
    id: bbb222
    "@id": ex:nested
    "@container": "@id"
`

describe('the capability matrix', () => {
  // @lat: [[emitters#Emitters#Capability Matrix]]
  it('the two targets differ in exactly one entry', () => {
    const a = capabilitiesFor('context').capabilities
    const b = capabilitiesFor('context-inline').capabilities
    expect(a.map((c) => c.key)).toEqual(b.map((c) => c.key))
    const differing = a.filter((c, i) => c.level !== b[i]!.level)
    expect(differing.map((c) => c.key)).toEqual(['external-reference'])
    expect(a.find((c) => c.key === 'external-reference')!.level).toBe('full')
    expect(b.find((c) => c.key === 'external-reference')!.level).toBe('downgraded')
  })
})

describe('the context target', () => {
  // @lat: [[emitters#Emitters#Context Target]]
  it('references each context by IRI, with the model’s own terms last', () => {
    const { ir, source } = build(LAYERED)
    const result = emit(ir, { target: 'context', source })
    const context = (result.document['@context'] as unknown[])
    expect(context[0]).toBe(UPSTREAM)
    const own = context[context.length - 1] as Record<string, unknown>
    expect(Object.keys(own)).toContain('title')
    expect(result.text).toContain(UPSTREAM)
  })

  it('identifies itself as generated and names the model', () => {
    const { ir, source } = build(LAYERED, 'vocab.jsonld.yaml')
    const result = emit(ir, { target: 'context', source })
    expect(result.text.startsWith('// Generated by jsonld-modeler from vocab.jsonld.yaml')).toBe(
      true,
    )
    expect(result.text).toContain('ldm emit --target context')
  })

  it('names what the target cannot carry, rather than dropping it silently', () => {
    const { ir, source } = build(LAYERED)
    const result = emit(ir, { target: 'context', source })
    expect(result.text).toContain('Not carried by this target: documentation')
    expect(result.text).toContain('Not carried by this target: element-ids')
  })

  it('changes only at the term that changed', () => {
    const { ir, source } = build(STANDALONE)
    const before = emit(ir, { target: 'context', source }).text
    const changed = STANDALONE.replace('"@id": ex:author', '"@id": ex:creator')
    const after = emit(build(changed).ir, { target: 'context', source: build(changed).source }).text

    const diff = before
      .split('\n')
      .map((line, i) => [line, after.split('\n')[i]] as const)
      .filter(([a, b]) => a !== b)
    expect(diff).toHaveLength(1)
    expect(diff[0]![0]).toContain('ex:author')
  })

  it('is byte-identical on repeat', () => {
    const { ir, source } = build(STANDALONE)
    expect(emit(ir, { target: 'context', source }).text).toBe(
      emit(ir, { target: 'context', source }).text,
    )
  })
})

describe('the context-inline target', () => {
  // @lat: [[emitters#Emitters#Inlined Context Target]]
  it('produces a self-contained context with no external reference', () => {
    const { ir, source } = build(LAYERED)
    const result = emit(ir, { target: 'context-inline', source, resolveContext })
    const context = result.document['@context'] as Record<string, unknown>
    expect(Array.isArray(context)).toBe(false)
    expect(JSON.stringify(context)).not.toContain(UPSTREAM)
    // The absorbed context's terms are present.
    expect(context['homepage']).toEqual({ '@id': 'schema:url', '@type': '@id' })
  })

  it('reports the fork against the uses entry and at the top of the artifact', () => {
    const { ir, source } = build(LAYERED)
    const result = emit(ir, { target: 'context-inline', source, resolveContext })

    const finding = result.findings.find(
      (f) => f.ruleId === 'L1.downgrade-external-reference-forked',
    )!
    expect(finding).toBeDefined()
    expect(finding.pointer).toBe('/uses/0')
    expect(finding.file).toBe('model.jsonld.yaml')

    // And a comment at the top naming the context and the hash it came from.
    const header = result.text.split('\n').filter((l) => l.startsWith('//'))
    expect(header.join('\n')).toContain(UPSTREAM)
    expect(header.join('\n')).toContain('sha256-ZZZZ')
  })

  it('is byte-identical across runs against unchanged vendored copies', () => {
    const { ir, source } = build(LAYERED)
    const first = emit(ir, { target: 'context-inline', source, resolveContext })
    const second = emit(build(LAYERED).ir, {
      target: 'context-inline',
      source: build(LAYERED).source,
      resolveContext,
    })
    expect(second.text).toBe(first.text)
  })

  it('refuses to flatten a context that is not vendored', () => {
    const { ir, source } = build(LAYERED)
    const result = emit(ir, { target: 'context-inline', source })
    expect(result.findings.some((f) => f.ruleId === 'L1.context-not-vendored')).toBe(true)
  })
})

describe('the mode-1.0 downgrade', () => {
  // @lat: [[emitters#Emitters#Capability Matrix]]
  it('still emits the facet, and says what a 1.0 processor does instead', () => {
    const { ir, source } = build(MODE_10)
    const result = emit(ir, { target: 'context', source })

    const own = result.document['@context'] as Record<string, unknown>
    // The facet is emitted.
    expect((own['name'] as Record<string, unknown>)['@protected']).toBe(true)

    const finding = result.findings.find((f) => f.ruleId === 'L1.downgrade-facet-unsupported')!
    expect(finding).toBeDefined()
    expect(finding.pointer).toBe('/terms/name/@protected')
    expect(finding.message).toContain('a later context may redefine the term freely')
  })

  it('places a comment at the lossy position in the artifact', () => {
    const { ir, source } = build(MODE_10)
    const { text } = emit(ir, { target: 'context', source })
    const lines = text.split('\n')
    const facetLine = lines.findIndex((l) => l.includes('"@protected"'))
    expect(facetLine).toBeGreaterThan(0)
    // The comment sits immediately above the fact it concerns.
    expect(lines[facetLine - 1]).toContain('// "name" carries @protected')
  })

  it('reports a 1.1-only container the same way', () => {
    const { ir, source } = build(MODE_10)
    const result = emit(ir, { target: 'context', source })
    const container = result.findings.filter(
      (f) => f.ruleId === 'L1.downgrade-facet-unsupported' && f.subject === 'nested',
    )
    expect(container.length).toBeGreaterThan(0)
    expect(container[0]!.message).toContain('@container: @id')
  })

  it('both targets report it', () => {
    const { ir, source } = build(MODE_10)
    for (const target of ['context', 'context-inline'] as const) {
      const result = emit(ir, { target, source, resolveContext })
      expect(result.findings.some((f) => f.ruleId === 'L1.downgrade-facet-unsupported')).toBe(true)
    }
  })
})

describe('the version header', () => {
  // @lat: [[architecture#Architecture#Source of Truth]]
  it('names the version and the project when the artifact belongs to one', () => {
    const { ir, source } = build(STANDALONE)
    const result = emit(ir, {
      target: 'context',
      source,
      versionId: 'abcdef0123456789',
      projectName: 'suite',
    })
    expect(result.text).toContain(
      '// Version: abcdef0123456789, published by the project suite.',
    )
    golden('standalone.versioned.jsonld', result.text)
  })

  it('names the version alone when there is no project', () => {
    const { ir, source } = build(STANDALONE)
    const result = emit(ir, { target: 'context', source, versionId: 'abcdef0123456789' })
    expect(result.text).toContain('// Version: abcdef0123456789.')
    expect(result.text).not.toContain('published by the project')
  })

  // The unpublished header must be exactly what it was before versions existed.
  it('names no version at all when the artifact belongs to none', () => {
    const { ir, source } = build(STANDALONE)
    const result = emit(ir, { target: 'context', source })
    expect(result.text).not.toContain('Version:')
    // And it is byte-identical to the golden written before this change.
    golden('standalone.context.jsonld', result.text)
  })

  it('is still stripped to strict JSON, and still loads', async () => {
    const { ir, source } = build(STANDALONE)
    const result = emit(ir, {
      target: 'context',
      source,
      versionId: 'abcdef0123456789',
      projectName: 'suite',
    })
    const artifact = JSON.parse(stripComments(result.text)) as Record<string, unknown>
    expect(JSON.stringify(artifact)).not.toContain('Version:')
    await expect(jsonld.expand({ ...artifact, name: 'Ada' } as never)).resolves.toHaveLength(1)
  })

  it('retargets an existing version line rather than adding a second', () => {
    const { ir, source } = build(STANDALONE)
    const original = emit(ir, {
      target: 'context',
      source,
      versionId: 'abcdef0123456789',
      projectName: 'suite',
    }).text

    const retargeted = retargetVersionHeader(original, 'fedcba9876543210', 'suite')
    expect(retargeted).toContain('// Version: fedcba9876543210')
    expect(retargeted).not.toContain('abcdef0123456789')
    expect(retargeted.match(/^\/\/ Version:/gm)).toHaveLength(1)
    // And nothing but that line changed.
    expect(retargeted.replace(/^\/\/ Version:.*$/m, 'X')).toBe(
      original.replace(/^\/\/ Version:.*$/m, 'X'),
    )
  })

  it('adds a version line to an artifact that had none', () => {
    const { ir, source } = build(STANDALONE)
    const unversioned = emit(ir, { target: 'context', source }).text
    const versioned = retargetVersionHeader(unversioned, 'abcdef0123456789')
    expect(versioned).toContain('// Version: abcdef0123456789.')
    expect(() => JSON.parse(stripComments(versioned))).not.toThrow()
  })
})

describe('golden files', () => {
  // @lat: [[emitters#Emitters#Verification]]
  const models: Array<[string, string]> = [
    ['standalone', STANDALONE],
    ['layered', LAYERED],
    ['mode-1.0', MODE_10],
  ]
  it.each(models)('%s emits both targets without churn', (name, text) => {
    for (const target of ['context', 'context-inline'] as const) {
      const { ir, source } = build(text)
      const result = emit(ir, { target, source, resolveContext })
      golden(`${name}.${target}.jsonld`, result.text)
      // A golden file is only worth keeping if the artifact still parses.
      expect(() => parseArtifact(result.text)).not.toThrow()
    }
  })
})

describe('emitted contexts are executed, not only snapshotted', () => {
  // @lat: [[emitters#Emitters#Verification]]
  const example = JSON.parse(readFileSync(join(DOCUMENTS, 'ok.json'), 'utf8'))

  it.each(['context', 'context-inline'] as const)(
    'an independent implementation loads the %s artifact and round-trips an example',
    async (target) => {
      const { ir, source } = build(STANDALONE)
      const { text } = emit(ir, { target, source, resolveContext })

      // The artifact as written, minus the commentary, is what a consumer loads.
      const artifact = JSON.parse(stripComments(text)) as { '@context': unknown }

      const expanded = (await jsonld.expand(
        { ...artifact, ...example } as never,
      )) as unknown[]
      const compacted = (await jsonld.compact(
        expanded as never,
        artifact['@context'] as never,
      )) as Record<string, unknown>
      const reexpanded = (await jsonld.expand(compacted as never)) as unknown[]

      expect(normalize(reexpanded)).toEqual(normalize(expanded))
      // And the example did not silently empty.
      expect(expanded.length).toBeGreaterThan(0)
      expect(JSON.stringify(expanded)).toContain('https://example.org/ns#name')
    },
  )

  it('writes an artifact a consumer can load straight off disk', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'ldm-emit-'))
    dirs.push(dir)
    const { ir, source } = build(STANDALONE)
    const { text } = emit(ir, { target: 'context', source })
    const path = join(dir, 'context.jsonld')
    writeFileSync(path, stripComments(text))
    const loaded = JSON.parse(readFileSync(path, 'utf8'))
    await expect(jsonld.expand({ ...loaded, name: 'Ada' } as never)).resolves.toHaveLength(1)
  })
})

function normalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(normalize).sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)))
  }
  if (value === null || typeof value !== 'object') return value
  const out: Record<string, unknown> = {}
  for (const key of Object.keys(value as Record<string, unknown>).sort()) {
    out[key] = normalize((value as Record<string, unknown>)[key])
  }
  return out
}
