/**
 * The `shacl` target: the shapes layer as a SHACL shapes graph, in Turtle.
 *
 * It is emitted and executed by the same definition, which is the point: L3
 * parses this exact text and runs a SHACL engine with it, so a consumer running
 * the shipped file gets the verdict the tool gave. Turtle is written here rather
 * than by a library writer because a downgrade's comment must sit at the
 * property shape it concerns, and Turtle — unlike JSON — has comments.
 *
 * @lat: [[emitters#Emitters#Downstream Targets#SHACL Shapes]]
 */
import { FindingCollector } from '../findings/collector.js'
import type { Finding } from '../findings/finding.js'
import { resolutionPrefixes, type Ir, type IrField, type IrRange, type IrShape } from '../model/ir.js'
import { resolveFieldKey, shapeContext, modelActiveContext, resolveShapeFieldsIn } from '../shapes/fields.js'
import type { ActiveContext } from '../processor/types.js'
import type { SourceIndex } from '../source/index-file.js'
import { capabilitiesFor, type Downgrade } from './capability.js'

const SH = 'http://www.w3.org/ns/shacl#'
const RDF = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
const XSD = 'http://www.w3.org/2001/XMLSchema#'

export interface ShaclEmitOptions {
  source: SourceIndex
  resolveContext?: (iri: string) => unknown
  modelName?: string
  projectName?: string
  versionId?: string
  /** The version header line, as the context targets write it, minus its comment marker. */
  versionLine?: string
}

export interface ShaclEmitResult {
  target: 'shacl'
  text: string
  findings: Finding[]
  downgrades: Downgrade[]
}

/** The IRI a shape's node shape is minted at: the namespace base, the name, `Shape`. */
export function shapeIri(ir: Ir, shape: IrShape): string {
  const suffix = shape.name.endsWith('Shape') ? '' : 'Shape'
  return `${ir.namespace.base}${shape.name}${suffix}`
}

export function emitShacl(ir: Ir, options: ShaclEmitOptions): ShaclEmitResult {
  const findings = new FindingCollector()
  const downgrades: Downgrade[] = []
  const active = modelActiveContext(ir, {
    ...(options.resolveContext !== undefined ? { resolveContext: options.resolveContext } : {}),
  })
  // Field keys resolve against the full context, referenced contexts included,
  // exactly as validation resolves them.
  const shapes = resolveShapeFieldsIn(ir, active)

  if (shapes.length === 0) {
    findings.raise(
      'L1.shacl-no-shapes',
      options.source,
      '',
      'The model declares no shapes, so the shapes graph holds none. Declare `shapes:` to say which fields a class has.',
      { severity: 'info' },
    )
  }

  const prefixes: Record<string, string> = {
    sh: SH,
    rdf: RDF,
    xsd: XSD,
    ...resolutionPrefixes(ir),
  }
  const writer = new TurtleNames(prefixes)

  const body: string[] = []
  for (const shape of [...shapes].sort((a, b) => a.id.localeCompare(b.id))) {
    body.push(...emitShape(ir, shape, shapes, active, writer, options, findings, downgrades))
    body.push('')
  }

  const lines = [
    ...header(options, downgrades).map((line) => `# ${line}`),
    '',
    ...writer.used().map(([name, iri]) => `@prefix ${name}: <${iri}> .`),
    '',
    ...body,
  ]
  return {
    target: 'shacl',
    text: `${lines.join('\n').trimEnd()}\n`,
    findings: findings.all(),
    downgrades,
  }
}

function header(options: ShaclEmitOptions, downgrades: Downgrade[]): string[] {
  const lines = [
    `Generated by jsonld-modeler from ${options.modelName ?? 'the model'}. Do not edit.`,
    'Target: shacl. Regenerate with `ldm emit --target shacl`.',
  ]
  if (options.versionLine !== undefined) lines.push(options.versionLine)
  for (const capability of capabilitiesFor('shacl').capabilities) {
    if (capability.level === 'none') {
      lines.push(`Not carried by this target: ${capability.key} — ${capability.note}`)
    }
  }
  for (const downgrade of downgrades) {
    if (downgrade.artifactPointer === '') lines.push(`Downgrade: ${downgrade.comment}`)
  }
  return lines
}

function emitShape(
  ir: Ir,
  shape: IrShape,
  shapes: readonly IrShape[],
  active: ActiveContext | undefined,
  names: TurtleNames,
  options: ShaclEmitOptions,
  findings: FindingCollector,
  downgrades: Downgrade[],
): string[] {
  const aboveShape: string[] = []
  const statements: string[] = [`  a ${names.iri(`${SH}NodeShape`)}`]
  if (shape.targetIri !== null) statements.push(`  ${names.iri(`${SH}targetClass`)} ${names.iri(shape.targetIri)}`)
  if (shape.closed) {
    statements.push(`  ${names.iri(`${SH}closed`)} true`)
    // `rdf:type` is how a node says what it is; closing a shape never forbids it.
    statements.push(`  ${names.iri(`${SH}ignoredProperties`)} ( ${names.iri(`${RDF}type`)} )`)
  }
  if (shape.note !== undefined) statements.push(`  ${names.iri(`${SH}description`)} ${literal(shape.note)}`)

  const context = active === undefined ? undefined : shapeContext(ir, shape, active)
  const fields = [...shape.fields].sort(
    (a, b) => (a.termId ?? '\uffff').localeCompare(b.termId ?? '\uffff') || a.key.localeCompare(b.key),
  )
  for (const field of fields) {
    const emitted = emitField(ir, shape, field, shapes, context, names, options, findings, downgrades)
    if (emitted.property !== undefined) {
      statements.push([...emitted.comments.map((c) => `  # ${c}`), emitted.property].join('\n'))
    } else {
      // A field with no property shape has nowhere inside the shape to carry
      // its comment, so it goes directly above the shape.
      aboveShape.push(...emitted.comments.map((c) => `# ${c}`))
    }
  }

  return [...aboveShape, names.iri(shapeIri(ir, shape)), `${statements.join(' ;\n')} .`]
}

interface EmittedField {
  comments: string[]
  property?: string
}

function emitField(
  ir: Ir,
  shape: IrShape,
  field: IrField,
  shapes: readonly IrShape[],
  context: ActiveContext | undefined,
  names: TurtleNames,
  options: ShaclEmitOptions,
  findings: FindingCollector,
  downgrades: Downgrade[],
): EmittedField {
  const comments: string[] = []
  if (field.iri === null) {
    // Already an L1 finding at the field; the artifact says why it is absent.
    return {
      comments: [`"${field.key}" in shape "${shape.name}" resolves to no property, so no constraint is emitted for it.`],
    }
  }

  const definition = context === undefined ? undefined : resolveFieldKey(ir, shape, context, field.key).definition
  const container = definition?.container ?? []

  if (container.includes('@graph')) {
    const comment = `"${field.key}" is a @graph container: its values are in a named graph, which the shapes graph does not reach, so no constraint is emitted for it.`
    const finding = findings.raise(
      'L1.downgrade-shacl-graph-container',
      options.source,
      field.pointer,
      `The field "${field.key}" of shape "${shape.name}" cannot be checked by SHACL: "${field.key}" is a @graph container, so its values are in a named graph that a shapes graph does not reach. No constraint is emitted for it.`,
      { subject: field.key },
    )
    downgrades.push({ finding, artifactPointer: field.pointer, comment })
    return { comments: [`Downgrade: ${comment}`] }
  }

  const isList = container.includes('@list')
  let path = field.inverse
    ? `[ ${names.iri(`${SH}inversePath`)} ${names.iri(field.iri)} ]`
    : names.iri(field.iri)
  if (isList) {
    // A list's members are reached through its cells; the property itself holds
    // the head. Constraints then apply to each member.
    path = `( ${path} [ ${names.iri(`${SH}zeroOrMorePath`)} ${names.iri(`${RDF}rest`)} ] ${names.iri(`${RDF}first`)} )`
    if (field.min !== undefined || field.max !== undefined) {
      const comment = `"${field.key}" is a @list: SHACL counts its distinct members, not its positions, so a repeated member counts once.`
      const finding = findings.raise(
        'L1.downgrade-shacl-list-cardinality',
        options.source,
        field.pointer,
        `The cardinality of "${field.key}" in shape "${shape.name}" is emitted over the list's members, and SHACL counts distinct members rather than positions: a list repeating a member satisfies less than it appears to.`,
        { subject: field.key },
      )
      downgrades.push({ finding, artifactPointer: field.pointer, comment })
      comments.push(`Downgrade: ${comment}`)
    }
  }

  const parts = [`${names.iri(`${SH}path`)} ${path}`]
  if (field.min !== undefined && field.min > 0) parts.push(`${names.iri(`${SH}minCount`)} ${field.min}`)
  if (field.max !== undefined) parts.push(`${names.iri(`${SH}maxCount`)} ${field.max}`)
  if (field.range !== undefined) parts.push(...rangeConstraints(ir, field.range, shapes, names))
  if (field.note !== undefined) parts.push(`${names.iri(`${SH}description`)} ${literal(field.note)}`)

  return { comments, property: `  ${names.iri(`${SH}property`)} [\n    ${parts.join(' ;\n    ')}\n  ]` }
}

function rangeConstraints(
  ir: Ir,
  range: IrRange,
  shapes: readonly IrShape[],
  names: TurtleNames,
): string[] {
  const kind = (value: string) => [`${names.iri(`${SH}nodeKind`)} ${names.iri(`${SH}${value}`)}`]
  switch (range.kind) {
    case 'iri':
      return kind('IRI')
    case 'node':
      return kind('BlankNodeOrIRI')
    case 'literal':
      return kind('Literal')
    case 'langString':
      return [`${names.iri(`${SH}datatype`)} ${names.iri(`${RDF}langString`)}`]
    case 'datatype':
      return [`${names.iri(`${SH}datatype`)} ${names.iri(range.iri)}`]
    case 'class':
      return range.iri === null ? [] : [`${names.iri(`${SH}class`)} ${names.iri(range.iri)}`]
    case 'shape': {
      const target = shapes.find((s) => s.id === range.shapeId)
      return target === undefined ? [] : [`${names.iri(`${SH}node`)} ${names.iri(shapeIri(ir, target))}`]
    }
  }
}

function literal(value: string): string {
  return JSON.stringify(value)
}

/**
 * Prefixed names where the local part is safe to write bare, full IRIs
 * otherwise. Only prefixes actually used are declared, so an unused prefix
 * does not become noise in a review.
 */
class TurtleNames {
  private readonly usedNames = new Set<string>()
  private readonly byLength: Array<[string, string]>

  constructor(private readonly prefixes: Record<string, string>) {
    // The longest namespace wins, so `schema:` does not shadow a deeper one.
    this.byLength = Object.entries(prefixes).sort((a, b) => b[1].length - a[1].length)
  }

  iri(value: string): string {
    for (const [name, namespace] of this.byLength) {
      if (!value.startsWith(namespace)) continue
      const local = value.slice(namespace.length)
      if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(local)) continue
      this.usedNames.add(name)
      return `${name}:${local}`
    }
    return `<${value}>`
  }

  used(): Array<[string, string]> {
    return [...this.usedNames].sort().map((name) => [name, this.prefixes[name]!])
  }
}

